import imp
from unittest import runner
from test_mathfunc import TestMathFunc
import unittest
from HTMLTestRunner import HTMLTestRunner


def main():
    suite = unittest.TestSuite()

    # tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
    # suite.addTests(tests)

    # suite.addTest(TestMathFunc("test_multi"))
    # suite.addTests(unittest.TestLoader().loadTestsFromName("test_mathfunc.TestMathFunc"))
    # suite.addTests(unittest.TestLoader().loadTestsFromNames(["test_mathfunc.TestMathFunc"]))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # with open("unittestTextReport.txt", 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)
    # with open("HTMLReport.html", 'wb') as f:
    #     runner = HTMLTestRunner(
    #         stream=f, title="MathFunc Test Report", description="generated by HTMLTestRunner", verbosity=2
    #     )
    #     runner.run(suite)

    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)


if __name__ == '__main__':
    main()
